server:
  port: 8080
  mode: dev
postgres:
  host: localhost
  port: 5433
  database: user_service
  user: root
  password: mysecretpassword
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
nats:
  host: localhost
  port: 4222
  streams:
    - name: EMAIL
      subjects:
        - EMAIL.*