// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Role struct {
	ID   int32
	Name string
}

type User struct {
	ID        int32
	Avatar    string
	Email     string
	Name      string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type UserLoginSession struct {
	Uuid        uuid.UUID
	UserID      int64
	PublicKey   string
	RfToken     string
	RfTokenUsed []string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type UserRole struct {
	UserID int32
	RoleID int32
}
