// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Role struct {
	ID   int32
	Name string
}

type User struct {
	ID       int32
	Avatar   pgtype.Text
	Email    string
	Name     pgtype.Text
	Password pgtype.Text
}

type UserRole struct {
	UserID int32
	RoleID int32
}
