// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package database

import (
	"context"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, avatar, email, name, password FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Avatar,
		&i.Email,
		&i.Name,
		&i.Password,
	)
	return i, err
}

const isUserExists = `-- name: IsUserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) IsUserExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, isUserExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
