// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (avatar, email, name, password)
VALUES ($1, $2, $3, $4)
RETURNING id, avatar, email, name, password, created_at, updated_at
`

type CreateUserParams struct {
	Avatar   string
	Email    string
	Name     string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Avatar,
		arg.Email,
		arg.Name,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Avatar,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserLoginSession = `-- name: CreateUserLoginSession :one
INSERT INTO user_login_session (uuid, user_id, public_key, rf_token, rf_token_used)
VALUES ($1, $2, $3, $4, $5)
RETURNING uuid, user_id, public_key, rf_token, rf_token_used, created_at, updated_at
`

type CreateUserLoginSessionParams struct {
	Uuid        uuid.UUID
	UserID      int64
	PublicKey   string
	RfToken     string
	RfTokenUsed []string
}

func (q *Queries) CreateUserLoginSession(ctx context.Context, arg CreateUserLoginSessionParams) (UserLoginSession, error) {
	row := q.db.QueryRow(ctx, createUserLoginSession,
		arg.Uuid,
		arg.UserID,
		arg.PublicKey,
		arg.RfToken,
		arg.RfTokenUsed,
	)
	var i UserLoginSession
	err := row.Scan(
		&i.Uuid,
		&i.UserID,
		&i.PublicKey,
		&i.RfToken,
		&i.RfTokenUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoginSessionByUserId = `-- name: GetLoginSessionByUserId :one
SELECT uuid, user_id, public_key, rf_token, rf_token_used, created_at, updated_at FROM user_login_session WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetLoginSessionByUserId(ctx context.Context, userID int64) (UserLoginSession, error) {
	row := q.db.QueryRow(ctx, getLoginSessionByUserId, userID)
	var i UserLoginSession
	err := row.Scan(
		&i.Uuid,
		&i.UserID,
		&i.PublicKey,
		&i.RfToken,
		&i.RfTokenUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, avatar, email, name, password, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Avatar,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isUserExists = `-- name: IsUserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) IsUserExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, isUserExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
