// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"music-streaming-microservices/email-service/internal/handler"
	"music-streaming-microservices/email-service/internal/repository"
)

// Injectors from wire.go:

func InitEmailHandler() handler.IHandler {
	iRepository := repository.NewRepository()
	iHandler := handler.NewHandler(iRepository)
	return iHandler
}
